ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml, --fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -i=4]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        args: [--fix]
        files: \.ts$
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@6.9.1"
          - "@typescript-eslint/parser@6.9.1"
          - eslint@8.53.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-import@2.29.0
          - typescript@5.2.2

exclude: .svg|dist/
