name: Setup git-cliff
description: Set up a specific version of git-cliff
author: Kenji Miyake
inputs:
  token:
    description: The token for GitHub API
    default: ${{ github.token }}
    required: false
  version:
    required: false
    description: The version of git-cliff
    default: latest
  target-platform:
    required: false
    description: The target platform
    default: x86_64-unknown-linux-gnu
runs:
  using: node20
  main: dist/index.js
