name: Setup git-cliff
description: Set up a specific version of git-cliff
author: Kenji Miyake
inputs:
  version:
    required: false
    description: The version of git-cliff
    default: latest
  target-platform:
    required: false
    description: The target platform
    default: x86_64-unknown-linux-gnu
runs:
  using: node16
  main: dist/index.js
