name: auto-version-update

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  auto-version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up yq
        uses: chrisdickinson/setup-yq@v1.0.1
        with:
          yq-version: v4.17.2

      - name: Get latest version
        id: get-latest-version
        run: |
          echo ::set-output name=latest-version::$(gh release list | grep -oP "Latest\s*v\K[0-9.]+")

      - name: Update version
        run: |
          yq -i e ".inputs.version.default=${{ steps.get-latest-version.outputs.latest-tag }}" action.yaml

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: ${{ github.event.repository.default_branch }}
          branch: auto-version-update
          title: "chore(release): auto version update"
          body: ""
          labels: ""
          assignees: ""
          reviewers: ""
          signoff: true
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
