name: npm-check-updates

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  npm-check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Update npm dependencies
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npx npm-check-updates -u --packageFile package.json
            npm install
            npm upgrade
            npm audit
            npm run build
          COMMIT_MESSAGE: "chore: update npm dependencies"
          PR_BRANCH_NAME: npm-check-updates
          PR_TITLE: "chore: update npm dependencies"
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
